apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    app: mcp-helper
  name: mcp-helper
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: mcp-helper
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mcp-helper
    spec:
      containers:
        - image: quay.io/maleck13/mcp-helper:latest
          imagePullPolicy: Always
          name: mcp-helper
          env:
            - name: SERVER1_URL
              value: 'http://mcp-test.mcp-server.svc.cluster.local:8081'
            - name: SERVER2_URL
              value: 'http://mcp-test.mcp-server.svc.cluster.local:8081'
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 50051
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
